[project]
name = "tidy-text-mining-zh"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "jieba>=0.42.1",
    "matplotlib>=3.10.9",
    "numpy>=2.4.4",
    "pandas>=3.0.3",
    "pyarrow>=24.0.0",
    "pyreadr>=0.5.6",
    "scikit-learn>=1.9.0",
    "seaborn>=0.13.2",
    "wordcloud>=1.9.6",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "jupyter-cache>=1.0.1",
]
